-- MySQL Workbench Synchronization
-- Generated: 2015-04-05 15:05
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Alfredo

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `clinica`.`log` 
CHANGE COLUMN `accion` `accion` VARCHAR(45) NOT NULL ,
ADD COLUMN `objeto` VARCHAR(511) NULL DEFAULT NULL AFTER `accion`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
